package com.whispertype.android.core.model

/** Aggregate, non-sensitive session metrics for diagnostics. */
data class DictationMetrics(
    val sessionId: SessionId,
    val startedAtMillis: Long,
    val endedAtMillis: Long? = null,
    val chunkCount: Int = 0,
    val bytesSent: Long = 0,
    val droppedChunks: Int = 0,
    val sendRejected: Int = 0,
    val finalizeLatencyMillis: Long? = null,
    val tapToCaptureMs: Long? = null,
    val tapToSetupCompleteMs: Long? = null,
    val tapToFirstAudioQueuedMs: Long? = null,
    val firstAudioToFirstTranscriptMs: Long? = null,
    val stopToCaptureQuiescedMs: Long? = null,
    val stopToActivityEndQueuedMs: Long? = null,
    val stopToTurnCompleteMs: Long? = null,
    val stopToSettledMs: Long? = null,
    val stopToInsertionResultMs: Long? = null,
    val insertionRequestedToResultMs: Long? = null,
    val acceptedFrames: Long = 0,
    val rejectedFrames: Long = 0,
    val inputTranscriptionCount: Long = 0,
    val outputTranscriptionCount: Long = 0,
    val maxWebSocketQueueSize: Int = 0,
    val turnCompleteArrived: Boolean = false,
    val usedHardDeadline: Boolean = false,
    val audioBufferOverflow: Boolean = false,
)